<%@ LANGUAGE=VBSCRIPT %>
<%
OPTION EXPLICIT
'-------------------------------
' 암호화 종류(1:AES, 2:DES, 3:SEED)
'-------------------------------
dim CRYPTO_MODE
CRYPTO_MODE = "3"

'-------------------------------
' API 버전정보
'-------------------------------
dim API_VERSION
API_VERSION = "0100"

'-------------------------------
' API 실행모드
' 0 : 테스트, 1 : 상용
'-------------------------------
dim RUN_MODE
RUN_MODE = "0"

'-------------------------------
' DLL 절대 경로
'-------------------------------
Dim DLL_PATH
DLL_PATH = "C:\\inetpub\\wwwroot\\credit-asp-link\\dll\\GxApiConf.ini"

'-------------------------------
' WORK TYPE
' 1: 실시간, 0: 배치처리
'-------------------------------
Dim WORK_TYPE
WORK_TYPE = "1"

'-------------------------------
' API COMMAND 정의
'-------------------------------
Dim COMMAND_ORDER_REQUEST, COMMAND_PIN_INQUIRY_REQUEST, COMMAND_ID_INQUIRY_REQUEST, COMMAND_CERTIFY_REQUEST, COMMAND_AUTO_BILL_CERTIFY_REQUEST
Dim COMMAND_IDENTITY_CERTIFY_REQUEST, COMMAND_AUTO_BILL_AGREE_CERTIFY_REQUEST, COMMAND_ID_CERTIFY_REQUEST, COMMAND_CERTIFY_SMS_REQUEST
Dim COMMAND_ARS_CERTIFY_REQUEST, COMMAND_AUTH_REQUEST, COMMAND_CERTIFY_AUTH_REQUEST, COMMAND_ID_CERTIFY_AUTH_REQUEST, COMMAND_PIN_CERTIFY_AUTH_REQUEST, COMMAND_ID_AUTH_REQUEST, COMMAND_AUTO_BILL_AUTH_REQUEST, COMMAND_AUTO_BILL_AGREE_AUTH_REQUEST
Dim COMMAND_IDENTITY_CONFIRM_REQUEST, COMMAND_BILL_REQUEST, COMMAND_AUTO_BILL_AGREE_BILL_REQUEST, COMMAND_ALARM_REQUEST, COMMAND_AUTH_MAIL_REQUEST
Dim COMMAND_AUTH_QUERY_REQUEST, COMMAND_REFUND_SMS_REQUEST, COMMAND_CANCEL_REQUEST, COMMAND_CANCEL_ADMIN_REQUEST, COMMAND_NETWORK_CANCEL_REQUEST
Dim COMMAND_CANCEL_SMS_REQUEST, COMMAND_CASHRECEIPT_REQUEST, COMMAND_CASHRECEIPT_BATCH_REQUEST, COMMAND_CASHRECEIPT_RESULT_REQUEST
Dim COMMAND_CERTIFY_QUERY_REQYEST

COMMAND_ORDER_REQUEST					= "0000"	'주문 요청
COMMAND_PIN_INQUIRY_REQUEST				= "1010"	'핀 조회 요청
COMMAND_ID_INQUIRY_REQUEST				= "1020"	'ID 조회 요청
COMMAND_CERTIFY_REQUEST					= "2000"	'인증 요청
COMMAND_AUTO_BILL_CERTIFY_REQUEST		= "2100"	'자동과금 인증 요청
COMMAND_IDENTITY_CERTIFY_REQUEST		= "2110"	'본인인증 요청
COMMAND_AUTO_BILL_AGREE_CERTIFY_REQUEST = "2120"	'자동과금  동의 인증 요청
COMMAND_ID_CERTIFY_REQUEST				= "2010"	'ID 인증 요청
COMMAND_CERTIFY_SMS_REQUEST				= "2200"	'인증 SMS 재 전송 요청
COMMAND_ARS_CERTIFY_REQUEST				= "2300"	'ARS데몬 인증 요청
COMMAND_AUTH_REQUEST					= "3000"	'승인 요청
COMMAND_ID_AUTH_REQUEST					= "3010"	'ID 승인 요청
COMMAND_AUTO_BILL_AUTH_REQUEST			= "3020"	'자동과금 승인 요청
COMMAND_AUTO_BILL_AGREE_AUTH_REQUEST	= "3030"	'자동 과금  동의 승인 요청
COMMAND_CERTIFY_AUTH_REQUEST			= "3040"	'인증 및 승인 요청
COMMAND_ID_CERTIFY_AUTH_REQUEST			= "3050"	'아이디 인증/승인 요청
COMMAND_PIN_CERTIFY_AUTH_REQUEST		= "3060"	'PIN 인증/승인 요청
COMMAND_IDENTITY_CONFIRM_REQUEST		= "3110"	'본인인증 확인 요청
COMMAND_BILL_REQUEST					= "3900"	'최종 과금 요청
COMMAND_AUTO_BILL_AGREE_BILL_REQUEST	= "3910"	'자동 과금  동의 과금 요청
COMMAND_AUTH_MAIL_REQUEST				= "4010"	'승인 메일 요청
COMMAND_AUTH_QUERY_REQUEST				= "5000"	'승인 내역 조회 요청
COMMAND_REFUND_SMS_REQUEST				= "8100"	'환불 SMS 요청
COMMAND_CANCEL_REQUEST					= "9000"	'취소 요청
COMMAND_NETWORK_CANCEL_REQUEST			= "9100"	'망취소 요청
COMMAND_CANCEL_SMS_REQUEST				= "9200"	'SMS 취소 요청
COMMAND_CASHRECEIPT_REQUEST				= "3200"	'현금영수증 데이터등록 요청
COMMAND_CASHRECEIPT_BATCH_REQUEST		= "3210"	'현금영수증 데이터 파일 등록 요청
COMMAND_CASHRECEIPT_RESULT_REQUEST		= "3220"	'현금영수증 처리결과 데이터 파일 요청
COMMAND_CERTIFY_QUERY_REQYEST			= "5100"	'인증 결과 확인 요청

'-------------------------------
' API SERVICE_CODE 정의
'-------------------------------
Dim SVCCODE_BOOKNLIFE_COUPON, SVCCODE_CULTURELAND_COUPON, SVCCODE_GAME_CULTURE_COUPON, SVCCODE_WISH_COUPON
Dim SVCCODE_HAPPYMONEY_COUPON, SVCCODE_MOBILE_PANGPANG, SVCCODE_CASHGATE, SVCCODE_ARS700, SVCCODE_CREDIT_CARD
Dim SVCCODE_ACCOUNT_TRANSFER, SVCCODE_MOBILE, SVCCODE_MOBILE_CANCEL, SVCCODE_PHONEBILL, SVCCODE_KTMPAY, SVCCODE_DOTORI_COUPON
Dim SVCCODE_CASH_RECEIPT, SVCCODE_T_MONEY, SVCCODE_ALARM

SVCCODE_BOOKNLIFE_COUPON	= "0100"
SVCCODE_CULTURELAND_COUPON	= "0200"
SVCCODE_GAME_CULTURE_COUPON	= "0300"
SVCCODE_WISH_COUPON			= "0400"
SVCCODE_HAPPYMONEY_COUPON	= "0500"
SVCCODE_MOBILE_PANGPANG		= "0600"
SVCCODE_CASHGATE			= "0700"
SVCCODE_ARS700				= "0800"
SVCCODE_CREDIT_CARD			= "0900"
SVCCODE_ACCOUNT_TRANSFER	= "1000"
SVCCODE_MOBILE				= "1100"
SVCCODE_MOBILE_CANCEL		= "1101"
SVCCODE_PHONEBILL			= "1200"
SVCCODE_KTMPAY				= "1300"
SVCCODE_DOTORI_COUPON		= "1400"
SVCCODE_CASH_RECEIPT		= "1500"
SVCCODE_T_MONEY				= "1600"
%>